# Generated by Django 5.1.7 on 2025-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, default='item_images/default.png', null=True, upload_to='item_images'),
        ),
    ]
