# Generated by Django 5.1.7 on 2025-03-28 21:06

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, default='item_images/default.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='item_images/'),
        ),
    ]
