# Generated by Django 5.1.7 on 2025-07-01 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_checkoutorder_email_alter_checkoutorder_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutorder',
            options={'ordering': ['-ordered_at'], 'verbose_name': 'order'},
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
