# Generated by Django 5.1.7 on 2025-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_checkoutorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
