# Generated by Django 5.1.7 on 2025-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_checkoutorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='chapa_tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
