# Generated by Django 5.1.7 on 2025-07-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_checkoutorder_chapa_tx_ref_checkoutorder_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutorder',
            name='chapa_tx_ref',
        ),
    ]
