# Generated by Django 5.1.7 on 2025-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_checkoutorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
