# Generated by Django 5.1.3 on 2025-03-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='converastion',
            new_name='conversation',
        ),
    ]
